#![allow(dead_code, clippy::too_many_arguments)]
//! Correctness test: compare meganeura SmolLM2-135M logits against PyTorch reference.
//!
//! Requires `bench/results/smollm2_ref_logits.bin` generated by:
//!   python bench/dump_smollm2_logits.py
//!
//! Run: cargo test --test smollm2_correctness -- --ignored

#[allow(dead_code, clippy::too_many_arguments)]
use meganeura::{Graph, build_inference_session, data::safetensors::SafeTensorsModel};
use std::collections::HashSet;

// ---------------------------------------------------------------------------
// Inlined SmolLM2 model
// ---------------------------------------------------------------------------
mod smollm2 {
    use meganeura::graph::{Graph, NodeId};

    pub struct SmolLM2Config {
        pub vocab_size: usize,
        pub hidden_size: usize,
        pub num_hidden_layers: usize,
        pub num_attention_heads: u32,
        pub num_key_value_heads: u32,
        pub intermediate_size: usize,
        pub rms_norm_eps: f32,
        pub rope_theta: f32,
    }

    impl SmolLM2Config {
        pub fn smollm2_135m() -> Self {
            Self {
                vocab_size: 49152,
                hidden_size: 576,
                num_hidden_layers: 30,
                num_attention_heads: 9,
                num_key_value_heads: 3,
                intermediate_size: 1536,
                rms_norm_eps: 1e-5,
                rope_theta: 10000.0,
            }
        }

        pub fn head_dim(&self) -> u32 {
            self.hidden_size as u32 / self.num_attention_heads
        }

        pub fn kv_dim(&self) -> usize {
            self.num_key_value_heads as usize * self.head_dim() as usize
        }
    }

    pub fn build_graph(g: &mut Graph, config: &SmolLM2Config, seq_len: usize) -> NodeId {
        let hidden = config.hidden_size;
        let kv_dim = config.kv_dim();
        let ffn = config.intermediate_size;
        let eps = config.rms_norm_eps;
        let theta = config.rope_theta;

        let token_ids = g.input_u32("token_ids", &[seq_len]);
        let embed_weight = g.parameter("model.embed_tokens.weight", &[config.vocab_size, hidden]);
        let mut x = g.embedding(token_ids, embed_weight);

        for i in 0..config.num_hidden_layers {
            let prefix = format!("model.layers.{}", i);

            let ln1_w = g.parameter(&format!("{}.input_layernorm.weight", prefix), &[hidden]);
            let h = g.rms_norm(x, ln1_w, eps);

            let wq = g.parameter(
                &format!("{}.self_attn.q_proj.weight", prefix),
                &[hidden, hidden],
            );
            let wk = g.parameter(
                &format!("{}.self_attn.k_proj.weight", prefix),
                &[hidden, kv_dim],
            );
            let wv = g.parameter(
                &format!("{}.self_attn.v_proj.weight", prefix),
                &[hidden, kv_dim],
            );

            let q = g.matmul(h, wq);
            let k = g.matmul(h, wk);
            let v = g.matmul(h, wv);

            let q = g.rope(q, theta, config.head_dim());
            let k = g.rope(k, theta, config.head_dim());

            let attn = g.causal_attention(
                q,
                k,
                v,
                config.num_attention_heads,
                config.num_key_value_heads,
                config.head_dim(),
            );

            let wo = g.parameter(
                &format!("{}.self_attn.o_proj.weight", prefix),
                &[hidden, hidden],
            );
            let attn_out = g.matmul(attn, wo);
            x = g.add(x, attn_out);

            let ln2_w = g.parameter(
                &format!("{}.post_attention_layernorm.weight", prefix),
                &[hidden],
            );
            let h = g.rms_norm(x, ln2_w, eps);

            let w_gate = g.parameter(&format!("{}.mlp.gate_proj.weight", prefix), &[hidden, ffn]);
            let w_up = g.parameter(&format!("{}.mlp.up_proj.weight", prefix), &[hidden, ffn]);
            let w_down = g.parameter(&format!("{}.mlp.down_proj.weight", prefix), &[ffn, hidden]);

            let gate = g.matmul(h, w_gate);
            let up = g.matmul(h, w_up);
            let ffn_out = g.swiglu(gate, up);
            let ffn_out = g.matmul(ffn_out, w_down);
            x = g.add(x, ffn_out);
        }

        let final_ln_w = g.parameter("model.norm.weight", &[hidden]);
        x = g.rms_norm(x, final_ln_w, eps);

        let lm_head = g.parameter("lm_head.weight", &[hidden, config.vocab_size]);
        g.matmul(x, lm_head)
    }

    pub fn transposed_weight_names(config: &SmolLM2Config) -> Vec<String> {
        let mut names = Vec::new();
        for i in 0..config.num_hidden_layers {
            let p = format!("model.layers.{}", i);
            names.push(format!("{}.self_attn.q_proj.weight", p));
            names.push(format!("{}.self_attn.k_proj.weight", p));
            names.push(format!("{}.self_attn.v_proj.weight", p));
            names.push(format!("{}.self_attn.o_proj.weight", p));
            names.push(format!("{}.mlp.gate_proj.weight", p));
            names.push(format!("{}.mlp.up_proj.weight", p));
            names.push(format!("{}.mlp.down_proj.weight", p));
        }
        names.push("lm_head.weight".to_string());
        names
    }
}
use smollm2::SmolLM2Config;

/// Reference values from PyTorch (HuggingFace transformers) with SmolLM2-135M.
/// Prompt: "The meaning of life is"
const TOKEN_IDS: &[u32] = &[504, 2455, 282, 1029, 314];
const SEQ_LEN: usize = 5;
const VOCAB_SIZE: usize = 49152;
/// Greedy argmax at each position from PyTorch.
const REF_GREEDY: &[u32] = &[808, 282, 260, 314, 288];

fn load_weights(
    session: &mut meganeura::Session,
    model: &SafeTensorsModel,
    config: &SmolLM2Config,
) {
    let transposed = smollm2::transposed_weight_names(config);
    let transposed_set: HashSet<&str> = transposed.iter().map(|s| s.as_str()).collect();

    for (name, _) in session.plan().param_buffers.clone() {
        // Skip fused parameters — auto-populated when source params are loaded
        if !model.tensor_info().contains_key(&name) && name != "lm_head.weight" {
            continue;
        }
        if name == "lm_head.weight" {
            if model.tensor_info().contains_key("lm_head.weight") {
                let data = if transposed_set.contains(name.as_str()) {
                    model.tensor_f32_auto_transposed(&name)
                } else {
                    model.tensor_f32_auto(&name)
                };
                session.set_parameter(&name, &data.unwrap_or_else(|e| panic!("{name}: {e}")));
            } else {
                let data = model
                    .tensor_f32_auto_transposed("model.embed_tokens.weight")
                    .expect("embed_tokens");
                session.set_parameter("lm_head.weight", &data);
            }
        } else if transposed_set.contains(name.as_str()) {
            let data = model
                .tensor_f32_auto_transposed(&name)
                .unwrap_or_else(|e| panic!("{name}: {e}"));
            session.set_parameter(&name, &data);
        } else {
            let data = model
                .tensor_f32_auto(&name)
                .unwrap_or_else(|e| panic!("{name}: {e}"));
            session.set_parameter(&name, &data);
        }
    }
}

#[test]
#[ignore] // Requires model download + reference logits on disk
fn smollm2_logits_match_pytorch() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("warn"))
        .try_init()
        .ok();

    // Load reference logits
    let bin_path = "bench/results/smollm2_ref_logits.bin";
    let bin_data = std::fs::read(bin_path).unwrap_or_else(|e| {
        panic!(
            "Missing reference logits ({bin_path}): {e}\n\
             Run: python bench/dump_smollm2_logits.py"
        )
    });
    let ref_logits: Vec<f32> = bin_data
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    assert_eq!(ref_logits.len(), SEQ_LEN * VOCAB_SIZE);

    let config = SmolLM2Config::smollm2_135m();
    let mut g = Graph::new();
    let logits = smollm2::build_graph(&mut g, &config, SEQ_LEN);
    g.set_outputs(vec![logits]);

    let mut session = build_inference_session(&g);

    let model =
        SafeTensorsModel::download("HuggingFaceTB/SmolLM2-135M").expect("failed to download model");
    load_weights(&mut session, &model, &config);

    // Run inference
    session.set_input_u32("token_ids", TOKEN_IDS);
    session.step();
    session.wait();

    let mega_logits = session.read_output(SEQ_LEN * VOCAB_SIZE);
    assert_eq!(mega_logits.len(), SEQ_LEN * VOCAB_SIZE);

    // Compare per-position
    let mut greedy_match = 0;
    let mut total_max_err = 0.0_f32;

    for pos in 0..SEQ_LEN {
        let offset = pos * VOCAB_SIZE;
        let mega_pos = &mega_logits[offset..offset + VOCAB_SIZE];
        let ref_pos = &ref_logits[offset..offset + VOCAB_SIZE];

        let pos_max_err: f32 = mega_pos
            .iter()
            .zip(ref_pos)
            .map(|(a, b)| (a - b).abs())
            .fold(0.0, f32::max);

        let mega_argmax = mega_pos
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .unwrap()
            .0 as u32;

        if mega_argmax == REF_GREEDY[pos] {
            greedy_match += 1;
        }

        eprintln!(
            "pos {pos}: max_err={pos_max_err:.4e}, mega_argmax={mega_argmax}, ref={} [{}]",
            REF_GREEDY[pos],
            if mega_argmax == REF_GREEDY[pos] {
                "MATCH"
            } else {
                "MISMATCH"
            }
        );

        total_max_err = total_max_err.max(pos_max_err);
    }

    eprintln!("\nGreedy matches: {greedy_match}/{SEQ_LEN}");
    eprintln!("Overall max abs error: {total_max_err:.4e}");

    // Position 0 should be nearly exact (RoPE is identity at pos 0)
    let pos0_max_err: f32 = mega_logits[..VOCAB_SIZE]
        .iter()
        .zip(&ref_logits[..VOCAB_SIZE])
        .map(|(a, b)| (a - b).abs())
        .fold(0.0, f32::max);
    assert!(
        pos0_max_err < 0.01,
        "Position 0 should be very precise, got max_err={pos0_max_err:.4e}"
    );

    // At least 3/5 greedy tokens should match (f32 accumulation through
    // 30 layers on software Vulkan can diverge enough to flip close races)
    assert!(
        greedy_match >= 3,
        "Too few greedy matches: {greedy_match}/5 (expected >= 3)"
    );
}
